Update Error

diff --git a/fd-airflow/Error b/fd-airflow/Error
--- a/fd-airflow/Error
+++ b/fd-airflow/Error
@@ -1,93 +1,9 @@
-Started by user Testing CICD
-Obtained Jenkinsfile from git https://github.com/ghubpraveen/SampleWebApp.git
-[Pipeline] Start of Pipeline
-[Pipeline] node
-Running on Jenkins in /var/lib/jenkins/workspace/UAT
-[Pipeline] {
-[Pipeline] stage
-[Pipeline] { (Declarative: Checkout SCM)
-[Pipeline] checkout
-The recommended git tool is: /usr/bin/git
-using credential 73181498-27bd-411c-88b8-97251ad8e05f
-Cloning the remote Git repository
-Cloning repository https://github.com/ghubpraveen/SampleWebApp.git
- > /usr/bin/git init /var/lib/jenkins/workspace/UAT # timeout=10
-Fetching upstream changes from https://github.com/ghubpraveen/SampleWebApp.git
- > /usr/bin/git --version # timeout=10
- > git --version # 'git version 2.34.1'
-using GIT_ASKPASS to set credentials 
- > /usr/bin/git fetch --tags --force --progress -- https://github.com/ghubpraveen/SampleWebApp.git +refs/heads/*:refs/remotes/origin/* # timeout=10
- > /usr/bin/git config remote.origin.url https://github.com/ghubpraveen/SampleWebApp.git # timeout=10
- > /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
-Avoid second fetch
- > /usr/bin/git rev-parse refs/remotes/origin/UAT^{commit} # timeout=10
-Checking out Revision f562d49ecbf25938ad1d05218d1b854cf17012e5 (refs/remotes/origin/UAT)
- > /usr/bin/git config core.sparsecheckout # timeout=10
- > /usr/bin/git checkout -f f562d49ecbf25938ad1d05218d1b854cf17012e5 # timeout=10
-Commit message: "First sample"
-First time build. Skipping changelog.
-[Pipeline] }
-[Pipeline] // stage
-[Pipeline] withEnv
-[Pipeline] {
-[Pipeline] withEnv
-[Pipeline] {
-[Pipeline] stage
-[Pipeline] { (1. Extract Parameters from Merge)
-[Pipeline] script
-[Pipeline] {
-[Pipeline] sh
-+ git rev-parse HEAD
-[Pipeline] echo
+DEPLOY_DIR= "/home/praveen/app_scripts/"
+cp "$WAR_FILE" "$DEPLOY_DIR/SampleWebAPP-${COMMIT_HASH:0:7}.war"
 
-                    ======= Parameters Extracted =======
-                    BRANCH      : UAT
-                    COMMIT_HASH : f562d49ecbf25938ad1d05218d1b854cf17012e5
-                    BUILD_CAUSE : jenkins-bot
-                    REQUIRED    : Build
-                    BUILD_ENV   : uat
-                    ====================================
-                    
-[Pipeline] }
-[Pipeline] // script
-[Pipeline] }
-[Pipeline] // stage
-[Pipeline] stage
-[Pipeline] { (2. Write Params to File)
-[Pipeline] script
-[Pipeline] {
-[Pipeline] sh
-+ dirname /tmp/jenkins-params/UAT-build-params.env
-+ mkdir -p /tmp/jenkins-params
-[Pipeline] writeFile
-[Pipeline] echo
-✅ Params written to: /tmp/jenkins-params/UAT-build-params.env
-[Pipeline] sh
-+ cat /tmp/jenkins-params/UAT-build-params.env
-JOB_NAME=UAT
-BRANCH=UAT
-COMMIT_HASH=f562d49ecbf25938ad1d05218d1b854cf17012e5
-BUILD_ENV=uat
-REQUIRED=Build
-BUILD_CAUSE=jenkins-bot
-WORKSPACE=/var/lib/jenkins/workspace/UAT
-[Pipeline] }
-[Pipeline] // script
-[Pipeline] }
-[Pipeline] // stage
-[Pipeline] stage
-[Pipeline] { (3. Build WAR)
-[Pipeline] script
-[Pipeline] {
-[Pipeline] sh
-+ echo 📦 Reading params and building WAR...
-📦 Reading params and building WAR...
-+ bash /var/lib/jenkins/workspace/UAT/java_deployment.sh /tmp/jenkins-params/UAT-build-params.env
-bash: /var/lib/jenkins/workspace/UAT/java_deployment.sh: No such file or directory
-[Pipeline] }
-[Pipeline] // script
-[Pipeline] }
-[Pipeline] // stage
-[Pipeline] stage
-[Pipeline] { (4. Archive WAR)
-Stage "4. Archive WAR" skipped due to earlier failure(s)
+if [[-f "$DEPLOY_DIR/SampleWebApp-${COMMIT_HASH:0:7}.war"]]: then
+    echo "✅ WAR copied successfully!"
+else
+    echo "❌ WAR copy failed"
+    exit 1
+fi
